### ISSUE TITLE
Invalid babel plugin declaration in Readme

### ISSUE THREAD

**Issue by TeNNoX** [scurker/babel-plugin-transform-currency-operators#28]
```json
{ "plugins":  [ "transform-currency-operators", ["./imports/lib/currency.js"]  ] }
```
-> doesn't work, as "./imports/lib/currency.js" is not plugin

**So I tried correcting it to be an entry with options, [as defined](https://babeljs.io/docs/en/options#plugin-preset-entries)**
```json
{ "plugins": [
    [ "transform-currency-operators", ["./imports/lib/currency.js"]  ]
] }
```
or
```json
{ "plugins": [
    [ "transform-currency-operators", "./imports/lib/currency.js"  ]
] }
```
**But this results in the error:**
> .plugins[0][1] must be an object, false, or undefined

Actually, it should be an object with options:
```json
{ "plugins": [
    [ "transform-currency-operators", { "customCurrencyImport": "./imports/lib/currency.js"}  ]
] }
```
but for this, the code needs to be changed

**Comment by scurker** [comment]
This was primarily written around babel 6, and it looks like a lot of the configuration options have changed since then. I'll need to update how the plugin options are consumed and release a new major version.

**Comment by scurker** [comment]
[v2.0.0](https://www.npmjs.com/package/babel-plugin-transform-currency-operators) has been published with this change
